# Candidate ecological indicators for the Gulf of St. Lawrence
**Marie-Julie Roux**

marie-julie.roux@dfo-mpo.gc.ca

## Definition

Ecological indicators are synthetic measures of ecosystem status and functioning used to enumerate important ecosystem attributes and reduce ecosystem complexity (Large et al. 2015b)

Ecological indicators are selected to represent key ecosystem components and processes including energy flow, trophic dynamics, community structure and size distribution (Large et al. 2015a).

## First iteration (2019)

Develop and investigate a shortlist of candidate fisheries-independent survey-based ecological indicators for the EGSL that represent community structure and function in the EGSL.

Shortlisted:

### Mean Length (population)

Average length *L~mean~* of species *i* calculated by year and trawl station using individual length data:

$L_{\text{mean}} = \ \sum_{i}^{}{\frac{l_{i}}{N}(mm)}$

### Maximum Length (population)

Maximum length *L~max~* of individual species *i* calculated as the 95^th^ percentile of individual length measures by year and trawl station:

$L_{\max} = \ L_{95\%}(mm)$

### Mean and maximum lengths (community) (mean.length) (max.length)

Average and maximum length of all shrimp, crab, squid and fish species routinely sampled for size during the annual survey, including commercial and non-commercial species. Mean and maximum lengths were calculated for each trawl-year combination. Maximum length was calculated as the 95^th^ percentile of individual length measures (to remove large and infrequent outlier effects).

\*Next step (potential improvement): weigh length data for individual taxa by their respective catch contribution (biomass in each trawl) (ponderation)

### Community indicator: Invertebrates to fish ratio (Inv:Fish ratio)

The ratio of total invertebrates biomass to total fish biomass in each trawl. Individual trawl biomass was calculated and standardized in kg per km2, based on individual tow swept area (product of tow distance derived from tow duration and trawling speed and trawl horizontal opening or wing spread). !

### Fish community indicator: Pelagic to demersal ratio (P:D ratio)

Individual fish species were classified into four vertical habitat groupings: 1) benthic species living and feeding on the bottom; 2) demersal species living and feeding on or near the bottom; 3) benthopelagic species living and feeding near the bottom as well as in midwaters or near the surface; and 4) pelagic species living and feeding in midwaters or near the surface.

The P:D ratio is the biomass ratio of pelagic and benthopelagic fish to demersal and benthic fish in each trawl.

### Fish community indicator: Plankton and Benthivorous fish to fish and Shrimp consumers Ratio (PB:FS ratio)

Fish species were classified into four feeding categories: 1) Planktivorous; 2) Benthivorous; 3) Piscivorous one and two (where piscivorous-one refers to shrimp (micronekton) consumers and piscivorous-two refers to both shrimp and fish consumers); and 4) Detritivorous/Scavenger. Species that undergo ontogenetic dietary shifts were assigned to a feeding category based on their adult stage diet (e.g., *Sebastes sp*. switch from a planktivorous to a piscivorous diet with increasing size and were assigned to the piscivorous category).

The PB:FS ratio is the biomass ratio of lower trophic level fish (planktivorous and benthivorous) to higher trophic level fish (piscivores one and two and detritivores)adult stage.

### Community indicators: Functional guilds biomass

Fish and invertebrate species were classified into 11 functional guilds, adapted from (Baker and Hollowed 2014):

-   Planktivorous fish (F) (bio\_pkt.fish)

-   Benthivorous fish (F) (bio\_benthiv.fish)

-   Pelagic and Benthopelagic piscivores (F, I) (bio\_pel.bpel.pisc)

-   Demersal and Benthic piscivores (F, I) (bio\_dem.bent.pisc)

-   Parasitic and Detritivorous fish (F) (bio\_par.det)

-   Benthic infauna (I) (bio\_benthic.infauna)

-   Benthic motile invertebrates (I) (bio\_benthic.mot.inv)

-   Crab (I) (bio\_crab)

-   Demersal and benthic Micronekton (I) (bio\_dem.bent.micronekton)

-   Pelagic and benthopelagic Micronekton (I) (bio\_pel.bpel.micronekton)

-   Sessile invertebrates (I) (bio\_sess.inv)

The biomass of each functional guild was calculated for each trawl-year combination. Biomass trajectories for individual functional guilds, or ratios of functional guilds biomass to total biomass in each trawl-year, may be used as ecological indicators (e.g., the proportion of predatory fish in individual trawl (bio\_pel.bpel.pisc+bio\_dem.bent.pisc /Trawl.Biomass) (Coll et al. 2016).

### Species richness and diversity

For the purpose of evaluating species richness, invertebrate taxa belonging to the following three functional guilds were pooled into higher-order taxonomic groupings in order to minimise the effect of recently increasing taxonomic resolution for these guilds in the survey data:

1.  Sessile invertebrates were pooled into the following 11 groups: Actiniaria, Alyconacea, Ascidiacea, Bryozoa, Cirripedia, Crinoidea, Hydrozoa, Pennatulacea, Porifera, Scleractinia and Zoanthidea.

2.  Benthic motile invertebrates were pooled into the following 9 groups: Asteroidea, Cumacea, Echinoidea, Gastropoda, Holothuroidea, Hydrozoa, Ophiuroidea, Picnogonida and Polyplacophora.

3.  Benthic infauna were pooled into the following 10 groups: Bivalvia, Brachiopoda, Echiura, Isopoda, Nematoda, Nemertea, Polycheate, Priapulidae, Scaphopoda and Sipuncula.

This approach reduced the total number of individual taxa recorded in the trawl survey data in 2006-2018 from 477 to 252. Richness was calculated as the total number of individual taxa in each trawl-year combination. This index could be further improved by i) distinguishing commercial invertebrate taxa from the broader taxonomic groups described above; and ii) by further refining and standardising invertebrate taxonomic resolution, for example by identifying dominant taxa that should be distinguished to species versus infrequent taxa that could remain pooled into higher-order taxonomic groups.

Continuous improvement and standardisation of taxonomic resolution in the trawl survey data will also allow for the development of reliable, fisheries-independent species diversity indicators for the EGSL.

### Candidate indicator species: biomass of cold and warm water species groups (cold.indicator.bio, warm.indicator.bio)

The following species were identified as candidate indicator taxa for cold water habitat in the EGSL: Boreogadus saida, Artediellus uncinatus, Eumicrotremus terraenovae, Pandalus borealis and Reinhardtius hippoglossoides. The following species were identified as candidate indicator taxa for warm water habitat in the EGSL: Merluccius bilinearis, Illex illecebrosus, Argentina silus.

The biomass of each candidate indicator taxa in each trawl-year combination was calculated. These can be examined as individual indicator taxa or as indicator groups (by summing the biomass of all cold or warm indicator taxa for each trawl-year combination).

Next steps: Calculate frequency of occurrence and index of relative importance (IRI) for these taxa at different spatial scales. Calculate and examine trajectories of mean and max length for candidate indicator taxa. Produce and investigate the usefulness of a length-unbiased condition factor for candidate indicator taxa.

### 1/CV of total biomass

This could be an interesting one to compute when scaling up to AE boxes and the entire ecosystem. See (Coll et al. 2016) for details.

## References

Baker, M. R., and A. B. Hollowed. 2014. Delineating ecological regions in marine systems: Integrating physical structure and community composition to inform spatial management in the eastern Bering Sea. Deep Sea Research Part II: Topical Studies in Oceanography **109**:215-240.

Coll, M., L. Shannon, K. Kleisner, M. Juan-Jordá, A. Bundy, A. Akoglu, D. Banaru, J. Boldt, M. Borges, and A. Cook. 2016. Ecological indicators to capture the effects of fishing on biodiversity and conservation status of marine ecosystems. Ecological Indicators **60**:947-962.

Large, S. I., G. Fay, K. D. Friedland, and J. S. Link. 2015a. Critical points in ecosystem responses to fishing and environmental pressures. Marine Ecology Progress Series **521**:1-17.

Large, S. I., G. Fay, K. D. Friedland, and J. S. Link. 2015b. Quantifying patterns of change in marine ecosystem response to multiple pressures. PloS one **10**:e0119922.
